### PR TITLE
Fixes #29449 - add credentials for pulpcore

### PR DESCRIPTION
**Pull request by m-bucher**
Relates to https://github.com/Katello/katello/pull/8640

### CODE REVIEW

**Comment by ekohl** [comment]
Would you mind adding these to https://github.com/theforeman/smart_proxy_pulp/blob/master/settings.d/pulpcore.yml.example as well?

**Comment by m-bucher** [comment]
> Would you mind adding these to https://github.com/theforeman/smart_proxy_pulp/blob/master/settings.d/pulpcore.yml.example as well?

Done, thanks for the hint.

**Comment by ekohl** [comment]
Also have a look at the failures. They are related.

**Comment by m-bucher** [comment]
> Also have a look at the failures. They are related.

Yes, question for that: Should I add example settings here or omit it and test for `username` and `password`to be `nil` as it is now?
https://github.com/theforeman/smart_proxy_pulp/blob/e45bc2672b0b4206a5263236ce845cabe405f3d6/test/pulpcore_plugin_integration_test.rb#L18

**Comment by ekohl** [comment]
I assume they'll be optional so IMHO it's good to have two test cases. One with and one without.

**Pull request merged**
